name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.6.1
  get: ^4.6.5

  http: ^1.1.0
  shimmer: ^3.0.0
     
  #local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
